//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabalhoDudu.CalculadoraService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soap.exemplo/", ConfigurationName="CalculadoraService.CalculadoraService")]
    public interface CalculadoraService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TrabalhoDudu.CalculadoraService.gerarValoresResponse gerarValores(TrabalhoDudu.CalculadoraService.gerarValores request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TrabalhoDudu.CalculadoraService.gerarValoresResponse> gerarValoresAsync(TrabalhoDudu.CalculadoraService.gerarValores request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TrabalhoDudu.CalculadoraService.validarUsuarioSenhaResponse validarUsuarioSenha(TrabalhoDudu.CalculadoraService.validarUsuarioSenha request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TrabalhoDudu.CalculadoraService.validarUsuarioSenhaResponse> validarUsuarioSenhaAsync(TrabalhoDudu.CalculadoraService.validarUsuarioSenha request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TrabalhoDudu.CalculadoraService.somarResponse somar(TrabalhoDudu.CalculadoraService.somar request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TrabalhoDudu.CalculadoraService.somarResponse> somarAsync(TrabalhoDudu.CalculadoraService.somar request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gerarValores", WrapperNamespace="http://soap.exemplo/", IsWrapped=true)]
    public partial class gerarValores {
        
        public gerarValores() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gerarValoresResponse", WrapperNamespace="http://soap.exemplo/", IsWrapped=true)]
    public partial class gerarValoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.exemplo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int[] @return;
        
        public gerarValoresResponse() {
        }
        
        public gerarValoresResponse(int[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validarUsuarioSenha", WrapperNamespace="http://soap.exemplo/", IsWrapped=true)]
    public partial class validarUsuarioSenha {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.exemplo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.exemplo/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public validarUsuarioSenha() {
        }
        
        public validarUsuarioSenha(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validarUsuarioSenhaResponse", WrapperNamespace="http://soap.exemplo/", IsWrapped=true)]
    public partial class validarUsuarioSenhaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.exemplo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public validarUsuarioSenhaResponse() {
        }
        
        public validarUsuarioSenhaResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="somar", WrapperNamespace="http://soap.exemplo/", IsWrapped=true)]
    public partial class somar {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.exemplo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.exemplo/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        public somar() {
        }
        
        public somar(int arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="somarResponse", WrapperNamespace="http://soap.exemplo/", IsWrapped=true)]
    public partial class somarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.exemplo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public somarResponse() {
        }
        
        public somarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculadoraServiceChannel : TrabalhoDudu.CalculadoraService.CalculadoraService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculadoraServiceClient : System.ServiceModel.ClientBase<TrabalhoDudu.CalculadoraService.CalculadoraService>, TrabalhoDudu.CalculadoraService.CalculadoraService {
        
        public CalculadoraServiceClient() {
        }
        
        public CalculadoraServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculadoraServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculadoraServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculadoraServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrabalhoDudu.CalculadoraService.gerarValoresResponse TrabalhoDudu.CalculadoraService.CalculadoraService.gerarValores(TrabalhoDudu.CalculadoraService.gerarValores request) {
            return base.Channel.gerarValores(request);
        }
        
        public int[] gerarValores() {
            TrabalhoDudu.CalculadoraService.gerarValores inValue = new TrabalhoDudu.CalculadoraService.gerarValores();
            TrabalhoDudu.CalculadoraService.gerarValoresResponse retVal = ((TrabalhoDudu.CalculadoraService.CalculadoraService)(this)).gerarValores(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrabalhoDudu.CalculadoraService.gerarValoresResponse> TrabalhoDudu.CalculadoraService.CalculadoraService.gerarValoresAsync(TrabalhoDudu.CalculadoraService.gerarValores request) {
            return base.Channel.gerarValoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrabalhoDudu.CalculadoraService.gerarValoresResponse> gerarValoresAsync() {
            TrabalhoDudu.CalculadoraService.gerarValores inValue = new TrabalhoDudu.CalculadoraService.gerarValores();
            return ((TrabalhoDudu.CalculadoraService.CalculadoraService)(this)).gerarValoresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrabalhoDudu.CalculadoraService.validarUsuarioSenhaResponse TrabalhoDudu.CalculadoraService.CalculadoraService.validarUsuarioSenha(TrabalhoDudu.CalculadoraService.validarUsuarioSenha request) {
            return base.Channel.validarUsuarioSenha(request);
        }
        
        public bool validarUsuarioSenha(string arg0, string arg1) {
            TrabalhoDudu.CalculadoraService.validarUsuarioSenha inValue = new TrabalhoDudu.CalculadoraService.validarUsuarioSenha();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            TrabalhoDudu.CalculadoraService.validarUsuarioSenhaResponse retVal = ((TrabalhoDudu.CalculadoraService.CalculadoraService)(this)).validarUsuarioSenha(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrabalhoDudu.CalculadoraService.validarUsuarioSenhaResponse> TrabalhoDudu.CalculadoraService.CalculadoraService.validarUsuarioSenhaAsync(TrabalhoDudu.CalculadoraService.validarUsuarioSenha request) {
            return base.Channel.validarUsuarioSenhaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrabalhoDudu.CalculadoraService.validarUsuarioSenhaResponse> validarUsuarioSenhaAsync(string arg0, string arg1) {
            TrabalhoDudu.CalculadoraService.validarUsuarioSenha inValue = new TrabalhoDudu.CalculadoraService.validarUsuarioSenha();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((TrabalhoDudu.CalculadoraService.CalculadoraService)(this)).validarUsuarioSenhaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrabalhoDudu.CalculadoraService.somarResponse TrabalhoDudu.CalculadoraService.CalculadoraService.somar(TrabalhoDudu.CalculadoraService.somar request) {
            return base.Channel.somar(request);
        }
        
        public int somar(int arg0, int arg1) {
            TrabalhoDudu.CalculadoraService.somar inValue = new TrabalhoDudu.CalculadoraService.somar();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            TrabalhoDudu.CalculadoraService.somarResponse retVal = ((TrabalhoDudu.CalculadoraService.CalculadoraService)(this)).somar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrabalhoDudu.CalculadoraService.somarResponse> TrabalhoDudu.CalculadoraService.CalculadoraService.somarAsync(TrabalhoDudu.CalculadoraService.somar request) {
            return base.Channel.somarAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrabalhoDudu.CalculadoraService.somarResponse> somarAsync(int arg0, int arg1) {
            TrabalhoDudu.CalculadoraService.somar inValue = new TrabalhoDudu.CalculadoraService.somar();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((TrabalhoDudu.CalculadoraService.CalculadoraService)(this)).somarAsync(inValue);
        }
    }
}
